services:
  opencode:
    container_name: opencode
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/user
    volumes:
      - ~/.local/share/opencode/auth.json:/home/user/.local/share/opencode/auth.json
